const domaineTypes = {
  GET_DOMAINE: "GET_DOMAINE",
  STORE_DOMAINE: "STORE_DOMAINE",
  HANDLE_DOMAINE_CHANGE: "HANDLE_DOMAINE_CHANGE",
  STORE_FEATURES_TAGS: "STORE_FEATURES_TAGS",
  SET_TAG_MODE: "SET_TAG_MODE",
  SET_ACTION_TAB: "SET_ACTION_TAB",
};

export default domaineTypes;
