const geometrieTypes = {
  STORE_SELECTED_FEATURES: "STORE_SELECTED_FEATURES",

  SET_DRAW_PARAMS: "SET_DRAW_PARAMS",
  RESET_DRAW_PARAMS: "RESET_DRAW_PARAMS",

  STORE_EDIT_GEOM: "STORE_EDIT_GEOM",
  STORE_RELATIONS_FEATURES: "STORE_RELATIONS_FEATURES",
  STORE_NEW_OBJECT_INFOS: "STORE_NEW_OBJECT_INFOS",

  SAVE_NEW_GEOMETRY: "SAVE_NEW_GEOMETRY",
  SET_SUIVI_GEOM_COORDS: "SET_SUIVI_GEOM_COORDS",
};

export default geometrieTypes;
