const appProcessTypes = {
  // UX ACTIONS..............................
  SET_USER_LOG: "SET_USER_LOG",
  SET_OVERLAY_OPEN: "SET_OVERLAY_OPEN",
  SET_ACTION_COMPLETE: "SET_ACTION_COMPLETE",
  SET_SNACKBAR: "SET_SNACKBAR",

  // WINDOWS HANDLERS.........................
  HANDLE_WINDOW_OPEN: "HANDLE_WINDOW_OPEN",
  HANDLE_WINDOW_CHILDREN: "HANDLE_WINDOW_CHILDREN",
  SEND_POST_MESSAGE: "SEND_POST_MESSAGE",

  // LAYERS FORM..............................
  SET_OPEN: "SET_OPEN",
  SET_READ_ONLY: "SET_READ_ONLY",
  GET_EMPRISES: "GET_EMPRISES",
  STORE_EMPRISES: "STORE_EMPRISES",
  UPDATE_FORM: "UPDATE_FORM",

  // GENERIC FUNCTIONS........................
  ADD_NEW_OBJECT: "ADD_NEW_OBJECT",
  HANDLE_DELETE: "HANDLE_DELETE",
  GET_FEATURE: "GET_FEATURE",
  GET_CONFIGS_BY_TYPE: "GET_CONFIGS_BY_TYPE",
  STORE_CONFIGS_BY_TYPE: "STORE_CONFIGS_BY_TYPE",

  // SQL REQUESTS.............................
  GET_SQL_RESULT: "GET_SQL_RESULT",
  STORE_SQL_RESULT: "STORE_SQL_RESULT",
  STORE_SQL_REQUEST: "STORE_SQL_REQUEST",

  // SPEED DIAL CONTROL.......................
  SET_SQL_PAGES: "SET_SQL_PAGES",
  SET_CONTROLS: "SET_CONTROLS",

  // MODELS REQUESTS..........................
  ADD_NEW_MODEL: "ADD_NEW_MODEL",
  HANDLE_MODEL_DELETE: "HANDLE_MODEL_DELETE",
  UPDATE_MODEL_FORM: "UPDATE_MODEL_FORM",

  // DROPDOWN REQUESTS..........................
  UPDATE_DROPDOWN: "UPDATE_DROPDOWN",
  ADD_DATA_DROPDOWN: "ADD_DATA_DROPDOWN",
  DELETE_DATA_DROPDOWN: "DELETE_DATA_DROPDOWN",

  // TAGS ASSIGNMENT..........................
  GET_FEATURES_TAGS: "GET_FEATURES_TAGS",
  ADD_FEATURES_TAG: "ADD_FEATURES_TAG",
  REMOVE_FEATURES_TAG: "REMOVE_FEATURES_TAG",

  // EXTERNAL LAYER
  GET_LAYER_MODEL: "GET_LAYER_MODEL",
  SEND_EXTERNAL_LAYER: "SEND_EXTERNAL_LAYER",

  // SETTINGS..................................
  GET_INITIAL_SETTINGS: "GET_INITIAL_SETTINGS",

  // TASK MANAGER...............................
  GET_DATES_LIST: "GET_DATES_LIST",
  GET_TASKS_FROM_DATE: "GET_TASKS_FROM_DATE",
  GET_TASK_STATUS: "GET_TASK_STATUS",
};

export default appProcessTypes;
