const supportTypes = {
  // Support
  GET_SUPPORT: "GET_SUPPORT",
  STORE_SUPPORT: "STORE_SUPPORT",
  DELETE_SUPPORT_OBJECT: "DELETE_SUPPORT_OBJECT",
  INSERT_SUPPORT_OBJECT: "INSERT_SUPPORT_OBJECT",
  // Groupes
  GET_GROUPES: "GET_GROUPES",
  STORE_GROUPES: "STORE_GROUPES",
  SET_GROUPE_CHECK: "SET_GROUPE_CHECK",
  // Infras
  GET_INFRAS: "GET_INFRAS",
  STORE_INFRAS: "STORE_INFRAS",

  HANDLE_SUPPORT_CHANGE: "HANDLE_SUPPORT_CHANGE",

  DELETE_GROUPE_ORIGINE_EXTREMITE: "DELETE_GROUPE_ORIGINE_EXTREMITE",
};

export default supportTypes;
