const cableTypes = {
  // Cable
  GET_CABLE: "GET_CABLE",
  STORE_CABLE: "STORE_CABLE",
  INSERT_CABLE_OBJECT: "INSERT_CABLE_OBJECT",
  DELETE_CABLE_OBJECT: "DELETE_CABLE_OBJECT",

  // Tubes
  GET_TUBES: "GET_TUBES",
  STORE_TUBES: "STORE_TUBES",
  SET_TUBE_CHECK: "SET_TUBE_CHECK",

  // Fibres
  GET_FIBRES: "GET_FIBRES",
  STORE_FIBRES: "STORE_FIBRES",
  SET_FIBRE_HS: "SET_FIBRE_HS",

  HANDLE_CABLE_CHANGE: "HANDLE_CABLE_CHANGE",
};

export default cableTypes;
