const relationsTypes = {
  // RELATIONS..........................
  SET_SOURCE: "SET_SOURCE",
  STORE_MULTI_LINE_SELECT: "STORE_MULTI_LINE_SELECT",

  // CABLE..........................
  GET_RELATIONS_CABLE: "GET_RELATIONS_CABLE",
  GET_R_CABLES: "GET_R_CABLES",
  STORE_R_CABLES: "STORE_R_CABLES",
  STORE_PASSAGES: "STORE_PASSAGES",

  // GROUPE..........................
  GET_R_GROUPES: "GET_R_GROUPES",
  STORE_R_GROUPES: "STORE_R_GROUPES",

  // INFRA..........................
  GET_R_INFRAS: "GET_R_INFRAS",
  STORE_R_INFRAS: "STORE_R_INFRAS",

  // ORIGINE EXTREMITE..........................
  // Cable
  STORE_ORIGINE_CABLE: "STORE_ORIGINE_CABLE",
  STORE_EXTREMITE_CABLE: "STORE_EXTREMITE_CABLE",
  STORE_NDI_CHOICES: "STORE_NDI_CHOICES",
  // Groupe
  GET_ORIGINE_GROUPE: "GET_ORIGINE_GROUPE",
  GET_EXTREMITE_GROUPE: "GET_EXTREMITE_GROUPE",
  STORE_ORIGINE_GROUPE: "STORE_ORIGINE_GROUPE",
  STORE_EXTREMITE_GROUPE: "STORE_EXTREMITE_GROUPE",

  // CREATE..........................
  CREATE_R_INFRA: "CREATE_R_INFRA",
  CREATE_R_NDS: "CREATE_R_NDS",
  CREATE_R_NDI: "CREATE_R_NDI",

  // UPDATE...........................
  UPDATE_LOVAGE: "UPDATE_LOVAGE",
  STORE_NEW_LOVAGE: "STORE_NEW_LOVAGE",

  // DELETE..........................
  DELETE_RELATION: "DELETE_RELATION",
  DELETE_ORIGINE_EXTREMITE: "DELETE_ORIGINE_EXTREMITE",
  DELETE_LOCAL_ORIGINE_EXTREMITE: "DELETE_LOCAL_ORIGINE_EXTREMITE",
  DELETE_PTT_ORIGINE_EXTREMITE: "DELETE_PTT_ORIGINE_EXTREMITE",
  DELETE_GROUPE_OE_RELATIONS: "DELETE_GROUPE_OE_RELATIONS",
};

export default relationsTypes;
