const modelTypes = {
  GET_MODEL_BY_TYPE: "GET_MODEL_BY_TYPE",
  STORE_MODEL_BY_TYPE: "STORE_MODEL_BY_TYPE",
  HANDLE_MODEL_CHANGE: "HANDLE_MODEL_CHANGE",
  SET_EQUIPMENT: "SET_EQUIPMENT",
  SET_DIALOG_OPEN: "SET_DIALOG_OPEN",
};

export default modelTypes;
