const epissureTypes = {
  // STEPPER.............................
  SET_EMPLACEMENT: "SET_EMPLACEMENT",
  RESET_EMPLACEMENT: "RESET_EMPLACEMENT",
  SET_EPISSURE_CABLE: "SET_EPISSURE_CABLE",

  // GET DATA.............................
  GET_C_AFFECT_INFOS: "GET_C_AFFECT_INFOS",
  GET_C_AFFECT_DATA: "GET_C_AFFECT_DATA",
  GET_C_AFFECT_CABLES_DATA: "GET_C_AFFECT_CABLES_DATA",

  // STORE DATA.............................
  STORE_C_AFFECT_DATA: "STORE_C_AFFECT_DATA",
  STORE_C_AFFECT_DATA_ORIGIN: "STORE_C_AFFECT_DATA_ORIGIN",
  STORE_C_AFFECT_INFOS: "STORE_C_AFFECT_INFOS",
  STORE_C_AFFECT_CABLES_DATA: "STORE_C_AFFECT_CABLES_DATA",
  STORE_ATTRIBUTIONS_BY_CABLE: "STORE_ATTRIBUTIONS_BY_CABLE",

  // SET DATA.............................
  SET_CHECK: "SET_CHECK",
  SET_UNCHECK: "SET_UNCHECK",
  SET_TUBE_CHECK: "SET_TUBE_CHECK",
  SET_POSITION_FIBRES: "SET_POSITION_FIBRES",
  SET_EPISSURE_SNACKBAR: "SET_EPISSURE_SNACKBAR",

  // SAVE DATA.............................
  SAVE_C_AFFECT: "SAVE_C_AFFECT",
  SAVE_EPISSURE_ACTION_COMPLETE: "SAVE_EPISSURE_ACTION_COMPLETE",

  // Multiline menu actions.............................
  FREE_LINE_FULL: "FREE_LINE_FULL",
  FREE_LINE_LEFT: "FREE_LINE_LEFT",
  FREE_LINE_RIGHT: "FREE_LINE_RIGHT",
  ETAT_EPISSUREE: "ETAT_EPISSUREE",
  ETAT_PASSAGE: "ETAT_PASSAGE",
};

export default epissureTypes;
