const ptTechTypes = {
  // Pt_tech
  GET_PTT_TECH: "GET_PTT_TECH",
  STORE_PTT_TECH: "STORE_PTT_TECH",
  DELETE_PTT_OBJECT: "DELETE_PTT_OBJECT",
  INSERT_PTT_OBJECT: "INSERT_PTT_OBJECT",
  // Bpes
  GET_PTT_BPES: "GET_PTT_BPES",
  STORE_PTT_BPES: "STORE_PTT_BPES",
  SET_BPE_CHECK: "SET_BPE_CHECK",
  // Cassettes
  GET_PTT_CASSETTES: "GET_PTT_CASSETTES",
  STORE_PTT_CASSETTES: "STORE_PTT_CASSETTES",

  HANDLE_PTT_CHANGE: "HANDLE_PTT_CHANGE",
  DELETE_PTT_ORIGINE_EXTREMITE: "DELETE_PTT_ORIGINE_EXTREMITE",
};

export default ptTechTypes;
