const pluginsTypes = {
  SET_DISABLED: "SET_DISABLED",
  STORE_MATERIAL_REFERENCE_BPE: "STORE_MATERIAL_REFERENCE_BPE",
  STORE_MATERIAL_REFERENCE_CABLE: "STORE_MATERIAL_REFERENCE_CABLE",
  GET_MATERIAL_REFERENCE: "GET_MATERIAL_REFERENCE",
  POST_PROCESS_PLUGINS: "POST_PROCESS_PLUGINS",
  GET_PROCESS_PLUGINS: "GET_PROCESS_PLUGINS",
};

export default pluginsTypes;
